import { PageFrame } from "@/components/site/PageFrame";
import { DeepContent } from "@/components/site/DeepContent";

export default function Platform() {
  return (
    <PageFrame eyebrow="PLATFORM / 01" title={<>The layer between<br /><em>intent and action.</em></>} intro="Arbyter gives organizations a runtime boundary for AI agents: discover them, understand what they can do, translate policy into controls, and decide what happens when they act.">
      <DeepContent sections={[
        {eyebrow:"THE GOVERNANCE LAYER",title:"One boundary for an AI workforce.",body:<><p>AI agents are moving from experiments into real business workflows. They can read information, call APIs, update records, communicate externally, trigger jobs and make decisions inside systems that were previously operated by people. The operational question is no longer only whether an agent can complete a task. It is whether the organization can define, enforce and explain the boundary around that task.</p><p>Arbyter is designed as that boundary. It sits between organizational intent and agent execution, giving teams a place to discover agents, understand their capabilities, express policy, evaluate actions and preserve the resulting decision trail.</p></>},
        {eyebrow:"AGENT DISCOVERY",title:"Know what is actually acting.",body:<><p>Governance starts with visibility. Arbyter is designed to discover agents across internal infrastructure, APIs, MCP connections, cloud environments, AI platforms and applications. Discovery is not just a directory of names; the useful context is ownership, connection type, capabilities, tools, destinations and operational status.</p><p>This creates a workforce map that can become the foundation for governance. Instead of asking teams to remember every automation they deployed, organizations can establish a continuously useful inventory and then apply controls to the agents that matter.</p></>},
        {eyebrow:"IDENTITY & CONTEXT",title:"An action needs more than an agent name.",body:<><p>The same action can have different consequences depending on who owns an agent, what capability it is using, which system it is reaching and what data is involved. Arbyter's governance model therefore treats execution as contextual.</p><p>Identity, capability, tool, destination, organization policy and action context can meet at the runtime decision point. That context lets a rule be specific enough to enforce rather than remaining a document that nobody can apply consistently.</p></>},
        {eyebrow:"POLICY",title:"Turn organizational language into controls.",body:<><p>Business policies are usually written for people. Runtime systems need explicit conditions. Arbyter connects those two layers: a requirement such as requiring human review for a high-impact HR decision can become an enforceable runtime control.</p><p>The goal is not to replace policy teams or legal teams. It is to give their requirements an operational path into the systems where AI agents act, so a policy can produce a decision instead of remaining disconnected documentation.</p></>},
        {eyebrow:"RUNTIME ENFORCEMENT",title:"The decision happens where the action happens.",body:<><p>Arbyter can evaluate an action before it becomes an external outcome. Depending on the applicable controls, the decision can be allow, block, restrict, pause or require human approval. The exact decision is determined by the organization's configured rules and the context of the action.</p><p>This is different from discovering a problem after execution. Runtime governance creates a point where the organization can intervene before a sensitive action crosses its boundary.</p></>},
        {eyebrow:"HUMAN OVERSIGHT",title:"Put people at the decisions that require people.",body:<><p>Not every action needs a person. The useful model is selective human involvement. Routine, low-risk actions can follow established controls while high-impact or exceptional actions can be routed for approval.</p><p>This allows organizations to define where autonomy ends. A human approval step can become part of the runtime workflow rather than an informal message sent after an agent has already acted.</p></>},
        {eyebrow:"AUDIT",title:"Explain what happened after the fact.",body:<><p>Governance is incomplete if the organization cannot reconstruct a decision. Arbyter's model keeps an audit trail around the action, the relevant agent, the policy or control, the resulting decision and any human approval involved.</p><p>This makes investigation more concrete. Instead of asking why an agent behaved a certain way with only application logs, teams can inspect the governance context that surrounded the action.</p></>},
        {eyebrow:"SECURITY",title:"Governance and security meet at runtime.",body:<><p>AI agent security includes identity, permissions, tools, destinations, data access and unexpected behavior. Arbyter brings these considerations into the same action-time boundary used for policy enforcement.</p><p>The result is a control model that can be applied across agents rather than relying entirely on every individual agent developer to implement a separate set of safeguards.</p></>},
        {eyebrow:"INTEGRATIONS",title:"Connect the workforce you already have.",body:<><p>Organizations do not have one universal agent stack. Agents may be internal applications, third-party services, MCP-connected systems, API workflows, cloud workloads or custom software. Arbyter is structured around connector abstractions so governance can sit above those different execution surfaces.</p><p>The objective is a consistent governance model without requiring every agent to become the same technology underneath.</p></>},
        {eyebrow:"OPERATING MODEL",title:"From a few agents to a governed workforce.",body:<><p>The platform is designed to become more valuable as the number of agents grows. Discovery provides the map, governance defines the boundary, runtime decisions enforce it and audit provides the record. Together those layers create an operating model for an AI workforce.</p><p>Arbyter's central idea is simple: intelligence can move quickly, but organizational authority still needs a place to live.</p></>}
      ]} />
    </PageFrame>
  );
}