import { PageFrame } from "@/components/site/PageFrame";
import { DeepContent } from "@/components/site/DeepContent";

export default function Resources() {
  return (
    <PageFrame eyebrow="RESOURCES / 04" title={<>A practical library<br /><em>for governed AI.</em></>} intro="Use these resources to understand runtime governance, policy enforcement, agent discovery, security, compliance and operating an AI workforce.">
      <DeepContent sections={[
        {eyebrow:"RUNTIME GOVERNANCE",title:"Understand the layer between intent and execution.",body:<><p>Runtime governance is the practice of applying organizational boundaries when software takes action. For AI agents, this means evaluating actions with the context needed to determine whether they should proceed.</p><p>Our runtime governance material explains the concepts behind allow, block, restrict, pause and human approval decisions.</p></>},
        {eyebrow:"POLICY ENFORCEMENT",title:"Connect business rules to software behavior.",body:<><p>Policies are valuable only when the organization can apply them consistently. A useful policy framework identifies the action being governed, the conditions that matter, the required decision and the record that should remain afterward.</p><p>This resource area explores the path from plain-language organizational intent to executable runtime controls.</p></>},
        {eyebrow:"AGENT DISCOVERY",title:"Build an inventory before the workforce becomes invisible.",body:<><p>Agent discovery covers more than counting deployments. Teams need to understand who owns an agent, what it can access, how it connects to systems and which actions it can perform.</p><p>Discovery resources explain how an inventory can become the foundation for governance, monitoring and risk management.</p></>},
        {eyebrow:"AI AGENT SECURITY",title:"Treat agent authority as a security boundary.",body:<><p>Agent security includes identity, permissions, tool access, destinations, data exposure and behavior. Traditional application security remains important, but autonomous software adds a new question: what should this agent be allowed to do right now?</p><p>Security resources explore how runtime context can complement identity and access controls.</p></>},
        {eyebrow:"COMPLIANCE",title:"Translate requirements into operational controls.",body:<><p>Compliance teams often work in policy language while engineering teams work in implementation language. The gap can make it difficult to prove how a requirement affects an autonomous workflow.</p><p>These resources examine ways to connect requirements to runtime controls and preserve evidence of the resulting decisions.</p></>},
        {eyebrow:"HUMAN-IN-THE-LOOP",title:"Design approval around meaningful decisions.",body:<><p>Human oversight works best when it is attached to a defined class of actions rather than applied indiscriminately. A governance system can identify where human review is required and record what was approved.</p><p>This material covers approval boundaries, escalation and the relationship between automation and organizational authority.</p></>},
        {eyebrow:"MCP GOVERNANCE",title:"Understand the tool layer.",body:<><p>MCP-connected agents can reach tools that extend what a model can accomplish. Governance therefore needs to understand the connection, the available capability and the action being requested.</p><p>The MCP resource set explains how runtime policy can sit around tool use without requiring every tool to implement the same governance model.</p></>},
        {eyebrow:"ARCHITECTURE",title:"See how the pieces fit together.",body:<><p>A useful governance architecture separates discovery, identity, policy, evaluation, enforcement and audit while allowing them to share context.</p><p>Architecture resources explain how those pieces interact and why the runtime decision point is the central control boundary.</p></>},
        {eyebrow:"GLOSSARY",title:"Make the terminology concrete.",body:<><p>AI governance includes terms such as agent identity, capability, runtime policy, action context, human-in-the-loop, MCP governance and audit trail. A shared vocabulary helps product, engineering, security and compliance teams discuss the same system.</p><p>The glossary provides concise definitions and links each concept to deeper material.</p></>},
        {eyebrow:"FIELD GUIDES",title:"Move from concepts to operating practice.",body:<><p>The final step is operational. Teams need to decide what to discover, which agents require controls, which actions need approval and what evidence should be retained.</p><p>Field guides turn the concepts into practical workflows for teams building a governed AI workforce.</p></>}
      ]} />
    </PageFrame>
  );
}