import { Analytics } from '@vercel/analytics/next'
import type { Metadata, Viewport } from 'next'
import './globals.css'

// The CSP generated by proxy.ts contains a per-request nonce. Force the root
// layout to render dynamically so Next.js does not cache/static-render markup
// under a nonce that belongs to a different request.
export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
  title: 'Arbyter OS — Orchestrate. Govern. Secure.',
  description:
    'Enterprise AI governance and orchestration platform. Orchestrate AI agents, govern their behavior, monitor risk, and maintain compliance.',
  generator: 'v0.app',
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  themeColor: '#ffffff',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="light bg-background"
    >
      <body className="font-sans antialiased">
        {children}
        {process.env.NODE_ENV === 'production' && <Analytics />}
      </body>
    </html>
  )
}
