import { PageFrame } from "@/components/site/PageFrame";
import { DeepContent } from "@/components/site/DeepContent";

export default function UseCases() {
  return (
    <PageFrame eyebrow="USE CASES / 03" title={<>Govern AI where<br /><em>work actually happens.</em></>} intro="Different teams have different risks. The governance layer stays consistent while the policies and runtime boundaries change with the work.">
      <DeepContent sections={[
        {eyebrow:"FINANCE",title:"Govern sensitive financial actions.",body:<><p>Finance workflows can combine private information, payment systems and actions with material consequences. An agent may need access to data to perform useful work, but that does not mean every destination or transaction should be available without controls.</p><p>Arbyter can provide runtime boundaries around financial data access, payment-related actions, external destinations and separation-of-duties requirements.</p></>},
        {eyebrow:"HR",title:"Keep high-impact people decisions reviewable.",body:<><p>HR agents can summarize applications, retrieve workforce information and automate administrative workflows. Some decisions, however, have consequences for people and may require additional review.</p><p>A governance policy can identify those actions and route them through human approval instead of allowing an autonomous workflow to make the final decision without oversight.</p></>},
        {eyebrow:"ENGINEERING",title:"Control production and infrastructure actions.",body:<><p>Engineering agents can inspect repositories, modify code, operate infrastructure and interact with deployment systems. Their value comes from speed, but production access also creates a need for precise boundaries.</p><p>Runtime controls can distinguish routine development work from actions that affect production, sensitive infrastructure or protected repositories.</p></>},
        {eyebrow:"SALES",title:"Govern CRM and external communication.",body:<><p>Sales agents can enrich records, update CRM systems, draft communications and interact with customer information. Organizations may want different rules for reading information, changing records and communicating externally.</p><p>Arbyter provides a common decision layer so those boundaries can be enforced according to organizational policy.</p></>},
        {eyebrow:"SUPPORT",title:"Protect customer data while automating service.",body:<><p>Support agents often need customer context to resolve issues. That creates a balance between useful access and unnecessary exposure.</p><p>Runtime governance can constrain which records an agent can access, which actions it can perform and when a human should take over.</p></>},
        {eyebrow:"OPERATIONS",title:"Automate routine workflows without losing control.",body:<><p>Operations teams can have many agents performing repetitive work across internal tools. A central governance layer makes it possible to define consistent boundaries instead of implementing separate controls inside every automation.</p><p>As the workforce grows, discovery and policy coverage become increasingly important because undocumented automation can otherwise become difficult to reason about.</p></>},
        {eyebrow:"ENTERPRISE",title:"Create one model across many teams.",body:<><p>Large organizations rarely have a single AI platform. Different teams deploy different agents with different tools and owners.</p><p>Arbyter provides a common governance model across those environments: discover the workforce, identify its authority, apply organizational rules and retain the decision trail.</p></>},
        {eyebrow:"COMPLIANCE",title:"Move requirements closer to execution.",body:<><p>Compliance requirements are often separated from the systems that actually perform work. That gap becomes harder to manage when software can make autonomous decisions.</p><p>Arbyter is designed to connect organizational and regulatory requirements to runtime controls, creating a practical path from a documented requirement to an action-time decision.</p></>},
        {eyebrow:"MCP",title:"Govern agents connected to tools.",body:<><p>MCP can give agents access to tools and external capabilities. Governance therefore needs to consider not just the model but the tools available through the connection.</p><p>Arbyter's runtime model can treat MCP-connected tools as part of the action context and apply the same organizational boundary used for other execution surfaces.</p></>},
        {eyebrow:"MULTI-AGENT",title:"Coordinate a workforce without losing authority.",body:<><p>As organizations move from individual agents to multi-agent workflows, responsibility becomes distributed. One agent may research, another may execute and another may communicate the result.</p><p>A governance layer provides a consistent place to evaluate actions across that chain, so autonomy can scale without requiring authority to disappear into the workflow.</p></>}
      ]} />
    </PageFrame>
  );
}