export type ToolDefinition = {
  name: string
  description: string
  inputSchema: Record<string, unknown>
  outputSchema: Record<string, unknown>
  execute: (input: Record<string, unknown>) => Promise<unknown>
}

function isObject(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value)
}

export const tools: Record<string, ToolDefinition> = {
  generate_sales_report: {
    name: "generate_sales_report",
    description: "Generate the current sales report for the authenticated organization.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: { type: "object", properties: { report: { type: "string" } }, required: ["report"] },
    async execute() {
      return { report: "Mock sales report generated by Arbyter MVP." }
    },
  },
  send_email: {
    name: "send_email",
    description: "Send an email. The MVP implementation is deliberately mocked unless a connector is wired in later.",
    inputSchema: {
      type: "object",
      properties: {
        recipient: { type: "string" },
        subject: { type: "string" },
        text: { type: "string" },
      },
      required: ["recipient", "subject", "text"],
      additionalProperties: false,
    },
    outputSchema: { type: "object", properties: { sent: { type: "boolean" } }, required: ["sent"] },
    async execute(input) {
      if (!isObject(input) || typeof input.recipient !== "string" || typeof input.subject !== "string" || typeof input.text !== "string") {
        throw new Error("Invalid send_email tool input.")
      }
      return { sent: true, mocked: true, recipient: input.recipient }
    },
  },
}

export function getTool(name: string): ToolDefinition {
  const tool = tools[name]
  if (!tool) throw new Error(`Tool is not registered: ${name}`)
  return tool
}

export function validateToolInput(tool: ToolDefinition, input: Record<string, unknown>) {
  const schema = tool.inputSchema
  const required = Array.isArray(schema.required) ? schema.required : []
  for (const key of required) {
    if (!(key in input)) throw new Error(`Missing required tool input: ${String(key)}`)
  }
}
