import { assertJsonSchema, type JsonSchema } from "../validation/json-schema.ts"

export type ToolDefinition = {
  name: string
  description: string
  inputSchema: JsonSchema
  outputSchema: JsonSchema
  execute: (input: Record<string, unknown>) => Promise<unknown>
}

export const tools: Record<string, ToolDefinition> = {
  generate_sales_report: {
    name: "generate_sales_report",
    description: "Generate the current sales report for the authenticated organization.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: { type: "object", properties: { report: { type: "string" } }, required: ["report"], additionalProperties: false },
    async execute() { return { report: "Mock sales report generated by Arbyter MVP." } },
  },
  send_email: {
    name: "send_email",
    description: "Send an email. The MVP implementation is deliberately mocked unless a connector is wired in later.",
    inputSchema: {
      type: "object",
      properties: { recipient: { type: "string" }, subject: { type: "string" }, text: { type: "string" } },
      required: ["recipient", "subject", "text"], additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: { sent: { type: "boolean" }, mocked: { type: "boolean" }, recipient: { type: "string" } },
      required: ["sent"], additionalProperties: false,
    },
    async execute(input) { return { sent: true, mocked: true, recipient: input.recipient } },
  },
}

export function getTool(name: string): ToolDefinition {
  const tool = tools[name]
  if (!tool) throw new Error(`Tool is not registered: ${name}`)
  return tool
}

export function validateToolInput(tool: ToolDefinition, input: Record<string, unknown>) {
  assertJsonSchema(input, tool.inputSchema, `${tool.name} input`)
}

export function validateToolOutput(tool: ToolDefinition, output: unknown) {
  assertJsonSchema(output, tool.outputSchema, `${tool.name} output`)
}
